name: Get latest successful release
description: Get latest successful release
author: 'Recharge'

branding:
  icon: 'heart'
  color: 'green'

inputs:
  github-token:
    description: 'Your github token'
    required: true
  github-repo:
    description: 'Your github repository'
    required: true
  github-repo-owner:
    description: 'The github repository owner'
    required: true
  release-workflow-path:
    description: 'The path to the release workflow'
    required: true

outputs:
  latest-successful-release:
    description: The commit sha of the latest successful release
    value: ${{ steps.get-latest-successful-release.outputs.value }}

# runs:
#   using: composite
#   steps:
#     - name: Get the latest successful release
#       id: get-latest-successful-release
#       shell: bash
#       run:
#         echo "value=${LATEST_SUCCESSFUL_RELEASE}" >> "$GITHUB_OUTPUT"

runs:
  using: node20
  id: get-latest-successful-release
  main: 'dist/index.js'
